{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devops-platform-app.fullname" . }}
  labels:
    {{- include "devops-platform-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "devops-platform-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        {{- range .Values.networkPolicy.ingress }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - ports:
        - port: {{ .port }}
          protocol: {{ .protocol }}
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
